### ISSUE TITLE
Is there clean code for the one class NN?

### ISSUE THREAD

**Issue by Sorkanius** [raghavchalapathy/oc-nn#1]
I was wondering if you had any clean code for plug and play of the one class NN, I am interested in using it.

Thanks!

**Comment by raghavchalapathy** [comment]
This example given [here](https://github.com/raghavchalapathy/oc-nn/blob/master/README.md)  should run seamlessly in Google Colab
Hope this helps

**Comment by Sorkanius** [comment]
Will try it. Thank you so much!
