### ISSUE TITLE
requirements.txt doesn't support for install tensorflow

### ISSUE THREAD

**Issue by ThinhNgVhust** [raghavchalapathy/oc-nn#10]
It could be better if you add which version of tensorflow we should install. Just my comment. thanks

**Comment by ThinhNgVhust** [comment]
and which version of keras are you using ?

**Comment by drwi** [comment]
same issue with this code 👍

**Comment by raghavchalapathy** [comment]
You can find a organised  content here :) along with video tutorials and code explanations
https://raghavchalapathy.github.io/KDD-Tutorials-2020-Deep-Robust-Anomaly-Detection/

**Comment by drwi** [comment]
> You can find a organised content here :) along with video tutorials and code explanations
> https://raghavchalapathy.github.io/KDD-Tutorials-2020-Deep-Robust-Anomaly-Detection/

i actually try to make your code work outside google colab, not that easy... ^^

**Comment by ThinhNgVhust** [comment]
yeah :) but i ran it from my pc. Thanks the author for the knowledge
