### ISSUE TITLE
How to do a test?

### ISSUE THREAD

**Issue by ghost** [raghavchalapathy/oc-nn#2]
Hi, I was able to train the models and save them, but then I would like to be able to read the saved models and test them, how can I do that?
I can not understand how it assigns the predicted labels to the images.

**Comment by raghavchalapathy** [comment]
ok, you may choose a threshold for score of oc-nn for normal and anomalies and filter the test input based on the score obtained to assign the labels

**Comment by ghost** [comment]
I am using the RAE.  How can I select that threshold correctly?  Thank you very much for answering

**Comment by raghavchalapathy** [comment]
it depends on your dataset look the images which have high reconstruction
errors are anomalies so you decide where the threshold should be depending
on your data
